changesetIgnorePatterns:
  - "!./packages"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

preferDeferredVersions: true

yarnPath: .yarn/releases/yarn-sources.js
