name: CI

on: push

jobs:
  setup:
    runs-on
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mm
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history for Changesets
          fetch-depth: 0
          path: mm
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn install --immutable
        working-directory:
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

      # If changesets have been added with `yarn changeset add`, opens a pull request and publishes when it is merged
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@master
        with:
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}